bump gkbus version to '0.4.74'
reverted gkbus python to 3.10.11 so it matches GKFlasher:
had to enable 'allow-prereleases: true' to permit the GitHub action to download python from source rather than rely on the Azure cache where old versions are depreciated within a few months. 

this also prevented the warning message that started with python 3.10.17 (although it didn't appear to break anything):
C:\Users\dmg>"C:\Program Files (x86)\GKFlasher\gui.exe"
Could not create pixmap from assets\Siemens_T_Logo.ico

reverted to scapy 2.5.0 as gui failing to launch with error:
FileNotFoundError: Tcl data directory "C:\Program Files (x86)\GKFlasher\_tcl_data" not found.
[PYI-20332:ERROR] Failed to execute script 'pyi_rth__tkinter' due to unhandled exception!

fixed setuptools version to '80.3.1' to prevent future build automation problems.